version: '3.8'

services:
  app:
    image: ghcr.io/stoerti/quizmania:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/quizmania
      - AXON_AXONSERVER_SERVERS=axonserver
    ports:
      - '8080'
    depends_on:
      - db
      - axonserver
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "8080:8080"
  db:
    image: postgres:16.2
    container_name: db
    environment:
      - POSTGRES_USER=quizmania
      - POSTGRES_PASSWORD=quizmania
    ports:
      - '5432:5432'
  axonserver:
    image: axoniq/axonserver:2024.1.0-jdk-17
    hostname: axonserver
    environment:
      AXONIQ_AXONSERVER_STANDALONE: "true"
    #    volumes:
#      - axonserver-data:/data
#      - axonserver-events:/eventdata
#      - axonserver-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    healthcheck:
      test: "curl --fail --silent localhost:8024/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
